default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: lesson5_development
  username: postgres
  password: postgres
  host: 127.0.0.1

test:
  database: lesson5_test
  username: postgres
  password: postgres
  host: 127.0.0.1